[package]

name = 'el-macro'
version = '0.2.1'

edition = '2021'
rust-version = '1.75.0'

description = 'a dumb macro collection for anti-idiomatic rust programming'
authors = ['dimas']
license = 'MIT'


[lib]
path = 'source/lib.rs'
