[package]

name = 'el-macro'
version = '0.3.0'

edition = '2021'
rust-version = '1.75.0'

description = 'a dumb macro collection for anti-idiomatic rust programming'
authors = ['dimas']
repository = "https://github.com/dmitry-glvch/el-macro"
license = 'MIT'


[lib]
path = 'source/lib.rs'
